# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4851b3d36227b7352d3ab82960ab3c460c46788817b4e4379ec468d1a014b543f26f4a1de8f40ba0b10f9e13e7a67395ed42366d1578ca699c36965a9985e1b

test:
  secret_key_base: c3956fa9d85f6137a47d61eeaf035e749d3433a97b56cdd1b1f2dd7cfaa5a7d6326aad0f18f4dff310397c0300e85e12acfd9e06014b5b5a5d32b4bdbf1f794f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
